version: '3.4'

services:
  api:
    image: api
    volumes:
      - .:/app:z
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: >
      sh -c "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    networks:
      - common_network
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9201:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@localhost.localdomain
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_DISABLE_POSTFIX: "true"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - common_network

  postgres:
    container_name: postgres_container_a
    image: postgres:alpine
    volumes:
      - postgres:/data/postgres
      - /var/run/postgresql:/var/run/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - common_network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    env_file:
      - .env
    command: server --console-address ":9001" /data
    networks:
      - common_network

volumes:
  postgres:
  minio_storage:
  pgadmin-data:


networks:
  common_network:
    name: common_network
    driver: bridge
